-- MySQL Script generated by MySQL Workbench
-- Sat Mar 19 14:29:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Batch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Batch` (
  `idBatch` INT NOT NULL,
  `Batch_Type` VARCHAR(45) NOT NULL,
  `Course` VARCHAR(45) NOT NULL,
  `Class_Timing` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBatch`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `idStudent` INT NOT NULL,
  `Student_Name` VARCHAR(45) NOT NULL,
  `Student_Email` VARCHAR(45) NOT NULL,
  `Student_Mobile` INT NOT NULL,
  `Batch_idBatch` INT NOT NULL,
  PRIMARY KEY (`idStudent`),
  INDEX `fk_Student_Batch_idx` (`Batch_idBatch` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Batch`
    FOREIGN KEY (`Batch_idBatch`)
    REFERENCES `mydb`.`Batch` (`idBatch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Task` (
  `idTask` INT NOT NULL,
  `Solved` INT NOT NULL,
  `Pending` INT NOT NULL,
  `Batch_idBatch` INT NOT NULL,
  PRIMARY KEY (`idTask`),
  INDEX `fk_Task_Batch1_idx` (`Batch_idBatch` ASC) VISIBLE,
  CONSTRAINT `fk_Task_Batch1`
    FOREIGN KEY (`Batch_idBatch`)
    REFERENCES `mydb`.`Batch` (`idBatch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mentor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mentor` (
  `idMentor` INT NOT NULL,
  `Mentor_Name` VARCHAR(45) NULL,
  `Batch_idBatch` INT NOT NULL,
  PRIMARY KEY (`idMentor`),
  INDEX `fk_Mentor_Batch1_idx` (`Batch_idBatch` ASC) VISIBLE,
  CONSTRAINT `fk_Mentor_Batch1`
    FOREIGN KEY (`Batch_idBatch`)
    REFERENCES `mydb`.`Batch` (`idBatch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
